//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ============================================================================
// MIGRATION NOTE (cr-dotnet-1034 – Async GridView Data Binding):
// Rule: cr-dotnet-1034  Severity: HIGH  Category: performance-&-scalability
//
// Occurrence – Line 31 (original TakeAppointment.aspx.designer.cs):
//   BEFORE:
//     protected global::System.Web.UI.WebControls.GridView TDeptGrid;
//     Synchronous GridView server control with DataSource/DataBind() pattern
//     blocks request threads, degrading cloud scalability under load.
//
//   AFTER:
//     GridView server control removed. Data is now loaded asynchronously via
//     TakeAppointmentController.IndexAsync() using getdeptInfo_Async() DAL method
//     connected to Amazon RDS via RDS Proxy (RDS_PROXY_CONNECTION_STRING env var).
//     Results are rendered in Views/Patient/TakeAppointment.cshtml as a plain
//     HTML table, preventing thread pool exhaustion and enabling auto-scaling.
//
//   Active implementation: Controllers/TakeAppointmentController.cs (async)
//   Active view:           Views/Patient/TakeAppointment.cshtml
//   Async DAL method:      DAL/myDAL.cs → getdeptInfo_Async()
// ============================================================================
// MIGRATION NOTE (cr-dotnet-0026 – Web Forms Usage):
// This designer file (TakeAppointment.aspx.designer.cs) was auto-generated for
// the Web Forms TakeAppointment.aspx page.
// The page has been migrated to ASP.NET Core MVC (cr-dotnet-0026):
//
//   • TakeAppointment.aspx    → Views/Patient/TakeAppointment.cshtml (Razor View)
//   • TakeAppointment.aspx.cs → Controllers/TakeAppointmentController.cs (MVC Controller)
//
// Web Forms server controls removed (cr-dotnet-0026, cr-dotnet-1034):
//   protected global::System.Web.UI.WebControls.Label TDept
//     → TakeAppointmentViewModel.StatusMessage (rendered in Razor view)
//   protected global::System.Web.UI.WebControls.GridView TDeptGrid
//     → TakeAppointmentViewModel.DeptData (async-loaded, rendered as HTML table)
//
// System.Web.UI.WebControls namespace is not available in ASP.NET Core.
// All server-control field declarations have been removed.
// ============================================================================

namespace DBProject
{
    // Designer class retained for reference only.
    // All Web Forms server-control declarations have been removed as part of
    // the ASP.NET Core MVC migration (cr-dotnet-0026) and async data binding
    // fix (cr-dotnet-1034).
    //
    // cr-dotnet-1034 FIX – Occurrence (Line 31):
    //   BEFORE: protected global::System.Web.UI.WebControls.GridView TDeptGrid;
    //           Synchronous GridView server control.
    //   AFTER:  Removed. Data loaded asynchronously via getdeptInfo_Async()
    //           and rendered as HTML table in TakeAppointment.cshtml.
    //
    // cr-dotnet-0026 FIX:
    //   BEFORE: protected global::System.Web.UI.WebControls.Label TDept;
    //           protected global::System.Web.UI.WebControls.GridView TDeptGrid;
    //   AFTER:  Removed. Replaced by TakeAppointmentViewModel properties.
    [System.Obsolete("Migrated to Controllers/TakeAppointmentController.cs and Views/Patient/TakeAppointment.cshtml (cr-dotnet-0026, cr-dotnet-1034)")]
    public partial class TakeAppointment_Designer
    {
        // cr-dotnet-1034 / cr-dotnet-0026:
        // REMOVED: protected global::System.Web.UI.WebControls.Label TDept;
        //          → Replaced by TakeAppointmentViewModel.StatusMessage
        //
        // REMOVED: protected global::System.Web.UI.WebControls.GridView TDeptGrid;
        //          → Replaced by async TakeAppointmentViewModel.DeptData
        //            loaded via getdeptInfo_Async() connected to Amazon RDS.
    }
}
