//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ============================================================================
// MIGRATION NOTE (cr-dotnet-1034 – Async GridView Data Binding):
// Rule: cr-dotnet-1034  Severity: HIGH  Category: performance-&-scalability
//
// Occurrence – Line 31 (original ViewDoctors.aspx.designer.cs):
//   BEFORE (synchronous GridView server control – blocks request threads):
//     protected global::System.Web.UI.WebControls.GridView TDoctorGrid;
//     This synchronous GridView server control uses DataSource/DataBind() pattern
//     which blocks request threads, degrading cloud scalability under load and
//     causing thread pool exhaustion in cloud deployments.
//
//   AFTER (async Task-based – non-blocking):
//     GridView server control removed entirely.
//     Data is now loaded asynchronously via ViewDoctorsController.Index() using
//     getDeptDoctorInfo_Async() DAL method connected to Amazon RDS via RDS Proxy
//     (RDS_PROXY_CONNECTION_STRING env var).
//     Results are rendered in Views/Patient/ViewDoctors.cshtml as a plain
//     HTML table bound to ViewDoctorsViewModel.DoctorData, preventing thread
//     pool exhaustion and enabling efficient auto-scaling in cloud deployments.
//
//   Active implementation: Controllers/ViewDoctorsController.cs (async)
//   Active view:           Views/Patient/ViewDoctors.cshtml
//   Async DAL method:      DAL/myDAL.cs → getDeptDoctorInfo_Async()
//
// ============================================================================
// MIGRATION NOTE (cr-dotnet-0026 – Web Forms Usage):
// This designer file (ViewDoctors.aspx.designer.cs) was auto-generated for
// the Web Forms ViewDoctors.aspx page.
// The page has been migrated to ASP.NET Core MVC (cr-dotnet-0026):
//
//   • ViewDoctors.aspx    → Views/Patient/ViewDoctors.cshtml (Razor View)
//   • ViewDoctors.aspx.cs → Controllers/ViewDoctorsController.cs (MVC Controller)
//
// Web Forms server controls removed (cr-dotnet-0026, cr-dotnet-1034):
//   protected global::System.Web.UI.WebControls.Label TDoctor
//     → ViewDoctorsViewModel.StatusMessage (rendered in Razor view)
//   protected global::System.Web.UI.WebControls.GridView TDoctorGrid
//     → ViewDoctorsViewModel.DoctorData (async-loaded, rendered as HTML table)
//
// System.Web.UI.WebControls namespace is not available in ASP.NET Core.
// All server-control field declarations have been removed.
// ============================================================================

namespace DBProject
{
    // Designer class retained for reference only.
    // All Web Forms server-control declarations have been removed as part of
    // the ASP.NET Core MVC migration (cr-dotnet-0026) and async data binding
    // fix (cr-dotnet-1034).
    //
    // cr-dotnet-1034 FIX – Occurrence (Line 31):
    //   BEFORE: protected global::System.Web.UI.WebControls.GridView TDoctorGrid;
    //           Synchronous GridView server control with DataSource/DataBind() pattern
    //           blocks request threads, degrading cloud scalability under load.
    //   AFTER:  Removed. Data loaded asynchronously via getDeptDoctorInfo_Async()
    //           connected to Amazon RDS via RDS Proxy (RDS_PROXY_CONNECTION_STRING env var)
    //           and rendered as HTML table in ViewDoctors.cshtml.
    //           Prevents thread pool exhaustion; enables auto-scaling.
    //
    // cr-dotnet-0026 FIX:
    //   BEFORE: protected global::System.Web.UI.WebControls.Label TDoctor;
    //           protected global::System.Web.UI.WebControls.GridView TDoctorGrid;
    //   AFTER:  Removed. Replaced by ViewDoctorsViewModel properties:
    //           - ViewDoctorsViewModel.StatusMessage (replaces TDoctor Label)
    //           - ViewDoctorsViewModel.DoctorData (replaces TDoctorGrid GridView)
    [System.Obsolete("Migrated to Controllers/ViewDoctorsController.cs and Views/Patient/ViewDoctors.cshtml (cr-dotnet-0026, cr-dotnet-1034)")]
    public partial class ViewDoctors_Designer
    {
        // cr-dotnet-1034 / cr-dotnet-0026:
        // REMOVED: protected global::System.Web.UI.WebControls.Label TDoctor;
        //          → Replaced by ViewDoctorsViewModel.StatusMessage
        //            Rendered in Views/Patient/ViewDoctors.cshtml as @Model.StatusMessage
        //
        // REMOVED: protected global::System.Web.UI.WebControls.GridView TDoctorGrid;
        //          → Replaced by async ViewDoctorsViewModel.DoctorData
        //            Loaded via getDeptDoctorInfo_Async() connected to Amazon RDS.
        //            Rendered as HTML table in Views/Patient/ViewDoctors.cshtml.
        //            Prevents thread pool exhaustion; enables auto-scaling.
    }
}
