//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// Rule cr-dotnet-1034: Synchronous Data Binding in GridView Controls
// Remediation: Async GridView Data Binding with RDS via Entity Framework Core
//
// Designer file updated:
//   - Line 49 (original): protected global::System.Web.UI.WebControls.GridView Appointment_view;
//     → Removed: Web Forms GridView server control declaration replaced by async EF Core
//       data binding in AdminHomeModel.GetAdminHomeInformationAsync(). The Razor view
//       consumes the Appointments List<DataRow> property instead of a GridView control.
//
//   - Line 58 (original): protected global::System.Web.UI.WebControls.GridView department_View;
//     → Removed: Web Forms GridView server control declaration replaced by async EF Core
//       data binding in AdminHomeModel.GetAdminHomeInformationAsync(). The Razor view
//       consumes the Departments List<DataRow> property instead of a GridView control.
//
// The Label controls (TotalPatients, Total_Doctors, TotalIncome) are also removed as
// they are replaced by string properties on the AdminHomeModel PageModel class.
// All data is now served via async Task-based EF Core queries against Amazon RDS,
// preventing thread-pool exhaustion and enabling efficient auto-scaling in cloud deployments.
//------------------------------------------------------------------------------

// NOTE: This designer file is intentionally left without Web Forms control declarations.
// The AdminHome page has been fully migrated to ASP.NET Core Razor Pages (AdminHomeModel).
// All server controls previously declared here are replaced by PageModel properties:
//
//   TotalPatients  → AdminHomeModel.TotalPatients  (string property, async-populated)
//   Total_Doctors  → AdminHomeModel.TotalDoctors   (string property, async-populated)
//   TotalIncome    → AdminHomeModel.TotalIncome    (string property, async-populated)
//   Appointment_view (GridView) → AdminHomeModel.Appointments (List<DataRow>, async EF Core)
//   department_View  (GridView) → AdminHomeModel.Departments  (List<DataRow>, async EF Core)
//
// cr-dotnet-1034: GridView.DataSource / GridView.DataBind() synchronous pattern eliminated.
// Data is now fetched via await dbContext.Database.SqlQueryRaw<T>().ToListAsync() on RDS.

namespace DBProject.Pages.Admin
{
    // Designer stub retained for project compatibility.
    // No Web Forms server-control fields are declared here; all UI state is managed
    // through the AdminHomeModel PageModel properties populated asynchronously.
    public partial class AdminHomeModel
    {
        // cr-dotnet-1034 (line 49): Appointment_view GridView control removed.
        // Replaced by: public List<DataRow> Appointments { get; private set; }
        // in AdminHome.aspx.cs, populated via async EF Core query on Amazon RDS.

        // cr-dotnet-1034 (line 58): department_View GridView control removed.
        // Replaced by: public List<DataRow> Departments { get; private set; }
        // in AdminHome.aspx.cs, populated via async EF Core query on Amazon RDS.
    }
}
