//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
// Rule cr-dotnet-1034: Synchronous Data Binding in GridView Controls
//   Removed legacy System.Web.UI.WebControls.GridView control declarations.
//   Data binding is now performed asynchronously via OnGetAsync() in the PageModel,
//   and rendered through Razor HTML table markup instead of server-side GridView controls.

namespace DBProject {
    
    
    public partial class AdminHome {
        
        /// <summary>
        /// TotalPatients control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// Migrated: replaced System.Web.UI.WebControls.Label with Razor model property.
        /// </remarks>
        // protected global::System.Web.UI.WebControls.Label TotalPatients;
        
        /// <summary>
        /// Total_Doctors control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// Migrated: replaced System.Web.UI.WebControls.Label with Razor model property.
        /// </remarks>
        // protected global::System.Web.UI.WebControls.Label Total_Doctors;
        
        /// <summary>
        /// TotalIncome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// Migrated: replaced System.Web.UI.WebControls.Label with Razor model property.
        /// </remarks>
        // protected global::System.Web.UI.WebControls.Label TotalIncome;
        
        /// <summary>
        /// Appointment_view control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// Migrated: System.Web.UI.WebControls.GridView replaced with async Razor HTML table.
        /// Data is now bound asynchronously via OnGetAsync() using Amazon RDS Task-based API.
        /// </remarks>
        // protected global::System.Web.UI.WebControls.GridView Appointment_view;
        
        /// <summary>
        /// department_View control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// Migrated: System.Web.UI.WebControls.GridView replaced with async Razor HTML table.
        /// Data is now bound asynchronously via OnGetAsync() using Amazon RDS Task-based API.
        /// </remarks>
        // protected global::System.Web.UI.WebControls.GridView department_View;
    }
}
