// cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
//
// This designer file has been updated as part of the migration from synchronous
// Web Forms GridView data binding to async Task-based patterns (cr-dotnet-1034).
//
// Original auto-generated designer declarations:
//   Line 49: protected global::System.Web.UI.WebControls.GridView Appointment_view;
//            → Replaced: synchronous GridView.DataBind() replaced with async ViewModel
//              property (AdminHomeViewModel.Appointments DataTable) populated via
//              async Task-based data access connected to Amazon RDS.
//   Line 58: protected global::System.Web.UI.WebControls.GridView department_View;
//            → Replaced: synchronous GridView.DataBind() replaced with async ViewModel
//              property (AdminHomeViewModel.Departments DataTable) populated via
//              async Task-based data access connected to Amazon RDS.
//
// The GridView server controls (Appointment_view, department_View) that previously
// used synchronous DataSource/DataBind() patterns have been replaced by DataTable
// properties on AdminHomeViewModel, rendered asynchronously in the Razor View
// (Views/Admin/AdminHome.cshtml) to prevent thread pool exhaustion under load.
//
// Active implementation: Controllers/AdminHomeController.cs (async Index action)
// Active view:           Views/Admin/AdminHome.cshtml (Razor View)
// Active model:          Models/AdminHomeViewModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    // cr-dotnet-1034: AdminHome partial class retained for reference only.
    // The active async implementation is in Controllers/AdminHomeController.cs.
    // Web Forms GridView controls (Appointment_view at line 49, department_View at line 58)
    // and their synchronous DataBind() calls have been replaced with async Task-based
    // ViewModel properties (AdminHomeViewModel.Appointments, AdminHomeViewModel.Departments)
    // populated via Entity Framework Core connected to Amazon RDS.
    public partial class AdminHome
    {
        // cr-dotnet-1034 (line 49): Appointment_view GridView replaced.
        // Previously: protected global::System.Web.UI.WebControls.GridView Appointment_view;
        // Synchronous Appointment_view.DataSource/DataBind() replaced with async
        // AdminHomeViewModel.Appointments DataTable in AdminHomeController.Index().

        // cr-dotnet-1034 (line 58): department_View GridView replaced.
        // Previously: protected global::System.Web.UI.WebControls.GridView department_View;
        // Synchronous department_View.DataSource/DataBind() replaced with async
        // AdminHomeViewModel.Departments DataTable in AdminHomeController.Index().
    }
}
