// cr-dotnet-1034: Async GridView Data Binding with RDS via Entity Framework Core
//
// This designer file has been updated as part of the migration from synchronous
// Web Forms GridView data binding to async Task-based patterns (cr-dotnet-1034).
//
// Original auto-generated designer declaration:
//   Line 67: protected global::System.Web.UI.WebControls.GridView Manage;
//            → Replaced: synchronous GridView.DataBind() replaced with async ViewModel
//              property (ManageClinicViewModel.GridData DataTable) populated via
//              async Task-based data access in ManageClinicController connected to
//              Amazon RDS, preventing thread pool exhaustion under load and enabling
//              efficient auto-scaling in cloud deployments.
//
// The GridView server control (Manage) that previously used synchronous
// DataSource/DataBind() patterns (lines 40, 55, 75 in ManageClinic.aspx.cs)
// has been replaced by the GridData DataTable property on ManageClinicViewModel,
// rendered asynchronously in the Razor View (Views/Admin/ManageClinic.cshtml)
// to prevent thread pool exhaustion under load.
//
// Active implementation: Controllers/ManageClinicController.cs (async Index action)
// Active view:           Views/Admin/ManageClinic.cshtml (Razor View)
// Active model:          Models/ManageClinicViewModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    // cr-dotnet-1034: ManageClinic partial class retained for reference only.
    // The active async implementation is in Controllers/ManageClinicController.cs.
    // Web Forms GridView control (Manage at line 67) and its synchronous
    // DataBind() calls (lines 40, 55, 75 in ManageClinic.aspx.cs) have been
    // replaced with async Task-based ViewModel property (ManageClinicViewModel.GridData)
    // populated via Entity Framework Core connected to Amazon RDS.
    public partial class ManageClinic
    {
        // cr-dotnet-1034 (line 67): Manage GridView replaced.
        // Previously: protected global::System.Web.UI.WebControls.GridView Manage;
        // Synchronous Manage.DataSource/DataBind() (lines 40, 55, 75) replaced with
        // async ManageClinicViewModel.GridData DataTable in ManageClinicController.Index().

        // Other Web Forms controls retained as comments for reference:
        // protected global::System.Web.UI.WebControls.RadioButton Doctor;
        // protected global::System.Web.UI.WebControls.RadioButton Patient;
        // protected global::System.Web.UI.WebControls.RadioButton OtherStaff;
        // protected global::System.Web.UI.WebControls.TextBox txtSearch;
        // protected global::System.Web.UI.WebControls.Label Msg;
        // protected global::System.Web.UI.HtmlControls.HtmlGenericControl mydiv;
        // All replaced by ManageClinicViewModel properties in the MVC controller.
    }
}
