//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// Rule cr-dotnet-1034: Synchronous Data Binding in GridView Controls
// Remediation: Async GridView Data Binding with RDS via Entity Framework Core
//
// Designer file updated:
//   - Line 67 (original): protected global::System.Web.UI.WebControls.GridView Manage;
//     → Removed: Web Forms GridView server control declaration replaced by async EF Core
//       data binding in ManageClinicModel.LoadGridAsync(). The Razor view consumes the
//       GridData DataTable property instead of a GridView server control.
//       This eliminates synchronous DataSource/DataBind() calls that block request threads,
//       preventing thread-pool exhaustion and enabling efficient auto-scaling on Amazon RDS.
//
// All other Web Forms server-control declarations are also removed as the page has been
// fully migrated to ASP.NET Core Razor Pages (ManageClinicModel PageModel).
// Controls previously declared here are replaced by PageModel properties:
//
//   Doctor    (RadioButton) → ManageClinicModel.Category (string, BindProperty)
//   Patient   (RadioButton) → ManageClinicModel.Category (string, BindProperty)
//   OtherStaff(RadioButton) → ManageClinicModel.Category (string, BindProperty)
//   txtSearch (TextBox)     → ManageClinicModel.SearchQuery (string, BindProperty)
//   Msg       (Label)       → ManageClinicModel.Message (string property)
//   Manage    (GridView)    → ManageClinicModel.GridData (DataTable, async EF Core)
//   mydiv     (HtmlControl) → ManageClinicModel.DetailHtml (string property)
//
// cr-dotnet-1034 (line 67): GridView.DataSource / GridView.DataBind() synchronous
// pattern eliminated. Data is now fetched via:
//   await dbContext.Database.SqlQueryRaw<T>().ToListAsync()
// on Amazon RDS, preventing thread-pool exhaustion under cloud load.
//------------------------------------------------------------------------------

// NOTE: This designer file is intentionally left without Web Forms control declarations.
// The ManageClinic page has been fully migrated to ASP.NET Core Razor Pages (ManageClinicModel).

namespace DBProject.Pages.Admin
{
    // Designer stub retained for project compatibility.
    // No Web Forms server-control fields are declared here; all UI state is managed
    // through the ManageClinicModel PageModel properties populated asynchronously.
    public partial class ManageClinicModel
    {
        // cr-dotnet-1034 (line 67): Manage GridView control removed.
        // Replaced by: public DataTable GridData { get; private set; }
        // in ManageClinic.aspx.cs, populated via async EF Core queries on Amazon RDS:
        //   - DOCTOR  category: await dbContext.Database.SqlQueryRaw<DoctorGridRow>().ToListAsync()
        //   - PATIENT category: await dbContext.Database.SqlQueryRaw<PatientGridRow>().ToListAsync()
        //   - STAFF   category: await dbContext.Database.SqlQueryRaw<StaffGridRow>().ToListAsync()
    }
}
