<%--
    MIGRATION NOTE (cr-dotnet-0026 – Web Forms Usage):
    This file (PendingAppointment.aspx) has been migrated to ASP.NET Core MVC.

    Replacement files:
      • Views/Doctor/PendingAppointment.cshtml  (Razor View)
      • Controllers/PendingAppointmentController.cs (MVC Controller)
      • Models/PendingAppointmentViewModel.cs   (ViewModel)

    Web Forms patterns removed / replaced:
      Line 1 – <%@ Page Title="" Language="C#" MasterPageFile="~/Doctor/doctormaster.Master"
                        AutoEventWireup="true" CodeBehind="PendingAppointment.aspx.cs"
                        Inherits="doctor.pendingappointment" %>
               → @{ Layout = "~/Views/Shared/_DoctorLayout.cshtml"; } in Razor View

      <asp:Content ContentPlaceHolderID="head">  → @section head { ... } in Razor View
      <asp:Content ContentPlaceHolderID="Cp3">   → @section Cp3 { ... } in Razor View

      Line 22 – asp:GridView ID="pendingappointments"
        AutoGenerateSelectButton="True"           → Approve form POST
        AutoGenerateDeleteButton="True"           → Delete form POST
        OnRowCommand="update_appointment"         → PendingAppointmentController.Approve()
        OnRowDeleting="Delete_appointment"        → PendingAppointmentController.Delete()

    MIGRATION NOTE (cr-dotnet-1034 – Synchronous Data Binding in GridView Controls):
      Line 22 – asp:GridView ID="pendingappointments" with synchronous DataBind()
              → Replaced with async Task<IActionResult> Index() in PendingAppointmentController.cs
                using async EF Core data access (GetAllpendingappointments_DAL_Async) connected
                to Amazon RDS, preventing thread pool exhaustion under cloud load.

      Line 40 – pendingappointments.DataSource = DT; pendingappointments.DataBind();
              → Replaced with async ViewModel population:
                  var dt = await objDAL.GetAllpendingappointments_DAL_Async(did);
                  vm.Appointments = dt;
                No synchronous DataBind() – non-blocking async pattern enables
                efficient auto-scaling in cloud deployments.

    This .aspx file is retained for reference only.
    The active view is Views/Doctor/PendingAppointment.cshtml.
--%>
