//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
// Rule cr-dotnet-1034: Synchronous Data Binding in GridView Controls
//   Removed legacy System.Web.UI.WebControls.GridView control declaration.
//   Data binding is now performed asynchronously via OnGetAsync() in the PageModel,
//   and rendered through Razor HTML table markup instead of server-side GridView controls,
//   preventing thread pool exhaustion under cloud load.

namespace doctor {
    
    
    public partial class pendingappointment {
        
        /// <summary>
        /// pendingappointments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// Migrated: System.Web.UI.WebControls.GridView replaced with async Razor HTML table.
        /// Data is now bound asynchronously via OnGetAsync() using Amazon RDS Task-based API,
        /// preventing thread pool exhaustion under cloud load.
        /// </remarks>
        // protected global::System.Web.UI.WebControls.GridView pendingappointments;
    }
}
